AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS SAM Starter template

Globals:
  Function:
    Runtime: nodejs16.x
    Timeout: 3

Parameters:
  REGION:
    Type: String
    Default: "us-east-1"

Resources:
  ShutdownFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/shutdown
      Handler: app.lambdaHandler
      Policies:
        - EC2DescribePolicy: {}
        - Statement:
            - Sid: TerminateEC2InstancePolicy
              Effect: Allow
              Action:
                - ec2:TerminateInstances
              Resource: "*"
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
            Enabled: True
      Environment:
        Variables:
          Region: !Ref REGION
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        EntryPoints:
          - app.ts

Outputs:
  ShutdownFunction:
    Description: "Shutdown Lambda Function ARN"
    Value: !GetAtt ShutdownFunction.Arn
